### ISSUE TITLE
Vocabulary IRI generated from "Agendový" vocabulary type is wrong

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/mission-control#206]
It incorrectly handles non-ASCII characters.
![image](https://user-images.githubusercontent.com/718827/136779179-626e7470-ba38-4be3-b284-c671906db336.png)
For other types it is OK
![image](https://user-images.githubusercontent.com/718827/136779261-ad8a1da3-3115-45d3-87be-6bcfd200612f.png)

**Comment by karelklima** [comment]
@jakubklimek This was done by design as the original purpose of agenda vocabularies was to have IDs without diacritics (according to the legal definition of agenda codes).

This confusion related to "agenda" type vocabularies will go away though, we will most likely abandon them completely and replace them with just generics, as it seems that the original purpose of those vocabularies is not a good fit to the overall SGoV anymore.
