### ISSUE TITLE
Adding a vocabulary into a workspace should add all its imported vocabularies as well

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/mission-control#84]
To keep the workspace self-contained, whenever a vocabulary is added to the workspace, for each vocabulary from its transitive import closure:
1) nothing happens if the vocabulary is already part of the workspace
2) the vocabulary is added in R/O regime otherwise.

**Comment by karelklima** [comment]
OK. It would be great to have an endpoint in SGOV that would return the list of vocabularies that belong to the transitive closure. Otherwise I'd need to set up some awkward front end process that would gradually resolve and add dependencies. It's possible, but probably not very practical. What do you think?

**Comment by psiotwo** [comment]
@karelklima Man, You are reading my brain :-) I was just half-way proposing You one of two options, but You picked one of them before I finished putting things down  :-) 

So https://github.com/opendata-mvcr/sgov/issues/78 ?

**Comment by psiotwo** [comment]
Done. Example call:

curl --location --request GET 'https://kbss.felk.cvut.cz/sgov-server/vocabularies/školství/imports?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/'
